services:
  konsulent-api:
    build:
      context: ./konsulent-api
    container_name: konsulent-api
    ports:
      - "8000:8000"
    networks:
      - app-network

  mcp-llm-verktoy-api:
    build:
      context: ./mcp-llm-verktoy-api
    container_name: mcp-llm-verktoy-api
    ports:
      - "8002:8002"
    environment:
      - KONSULENT_API_URL=http://konsulent-api:8000
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
    depends_on:
      - konsulent-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
